waypoint_navigation:
  waypoint_navigation_node:
    ros__parameters:
      wps:
        - "1"
        - "7.68"
        - "-1.85"
        - "-0.03"
        - "1.0"

        - "2"
        - "7.84"
        - "-17.34"
        - "0.81"
        - "0.59"

        - "3"
        - "-0.28"
        - "-27.48"
        - "0.99"
        - "0.12"

        - "4"
        - "-8.54"
        - "-27.16"
        - "-0.78"
        - "0.67"

        - "5"
        - "-10.42"
        - "-33.74"
        - "-0.78"
        - "0.67"

        - "6"
        - "-10.88"
        - "5.86"
        - "-0.69"
        - "0.72"

        - "7"
        - "-4.50"
        - "16.58"
        - "0.00"
        - "1.0"

        - "8"
        - "4.55"
        - "19.94"
        - "0.53"
        - "0.85"

        - "9"
        - "8.97"
        - "13.39"
        - "0.76"
        - "0.65"

        - "10"
        - "10.62"
        - "6.18"
        - "0.99"
        - "0.12"
